body common control
{
      inputs => { "../../default.cf.sub" };
      bundlesequence  => { editor };
}

bundle agent editor
{
  vars:
        "null_shadow_entries"    ilist    =>    {4, 5, 6, 7, 8};

  files:
      "$(G.testfile)"
      handle => "null_root_user_account_expiration_shadow_entries",
      edit_line => set_user_field("root", $(null_shadow_entries), ""),
      classes => if_repaired("root_password_modified");
}
