#!/bin/sh

echo "^context=xyz" 
echo "+myclass"
echo "=myvar=hello there" 
echo "@mylist={\"abc\", \"def\", \"ghi\"}" 
echo "@myalist={\"{{abc}}\", \"  ' def}\", \"ghi'''\"}" 
echo "@myblist={'{{a,bc}}', '  \" de,f}', 'gh,,i\"\"\"'}" 
echo "@myclist={\"{{a'bc',,}}\", '  \",, d\"ef}', \"ghi,},'''\"}" 
echo '%mycontainer1={"x":[456,789]}'
echo '%mycontainer2={"x":"y"'
echo '%mycontainer3="long string here"'
echo '%mycontainer4=null'
echo '%mycontainer5=["read", "some", "strings"]'
echo '%mycontainer6={"mix": ["match"], "ping": "pong", "paddle": true, "nothing": null}'
