#######################################################
#
# Test that action => "warn" works correctly for rename { rotate => 1 } (Issue 841)
#
#######################################################

body common control
{
  inputs => { "../../default.cf.sub" };
  bundlesequence  => { "test" };
nova_edition::
  host_licenses_paid => "5";
}

#######################################################

bundle agent test
{
files:
  "$(G.testfile)"
     edit_line => append_nonsense,
     edit_defaults => rotate;
}

body edit_defaults rotate
{
  edit_backup => "rotate";
  rotate => "4";
  max_file_size => "300000";
}

bundle edit_line append_nonsense
{
vars:
  useless0::
    "contents" string => "0";
  useless1::
    "contents" string => "1";
  useless2::
    "contents" string => "2";
  useless3::
    "contents" string => "3";
  useless4::
    "contents" string => "4";

insert_lines:
  any::
    "$(contents)";
}

