#######################################################
#
# Test that action => "warn" works correctly for rename { rotate => 1 } (Issue 841)
#
#######################################################

body common control
{
  bundlesequence  => { "g", "test" };   
nova_edition::
  host_licenses_paid => "5";
}

bundle common g
{
vars:
  "testfile" string => "/tmp/TEST.cfengine";
}

#######################################################

bundle agent test
{
files:
  "$(g.testfile)"
   edit_line => append_nonsense,
	edit_defaults => rotate;
}

body edit_defaults rotate
{
	edit_backup => "rotate";
	rotate => "4";
	max_file_size => "300000";	
}

bundle edit_line append_nonsense
{
vars:
  "ns" string => execresult("/bin/date +%N", "noshell");
insert_lines:
	"$(ns)";
}

