body file control
{
      namespace => "xxx";
}

bundle agent localclass
{
  reports:

    cfengine::
      "testing class 2"
      classes => always("a_class_global_from_command");

    a_class_global_from_command::
      "Global class from 'classes' attribute, accessed in the same namespace";
    default:a_class_global_from_command::
      "Global class from 'classes' attribute, accessed in the default namespace";
}

body classes always(x)

# Define a class no matter what the outcome of the promise is

{
      promise_repaired => { "$(x)" };
      promise_kept => { "$(x)" };
      repair_failed => { "$(x)" };
      repair_denied => { "$(x)" };
      repair_timeout => { "$(x)" };
      #  persist_time => "1";
}
