body file control
{
  namespace => "ns109";
}

bundle agent pass()
{
  vars:
      "class_needed" string => "shared_class";

      "shared_dependent" string => "works",
      ifvarclass => "$(class_needed)";

    shared_class::
      "forced_dependent" string => "works";

  reports:
    DEBUG::
      "Does the shared class work in a variable? Is '$(shared_dependent)' == 'works'?";

      "Does the shared class work explicitly? Is '$(forced_dependent)' == 'works'?";

      "The shared class claims to work."
      ifvarclass => "$(class_needed)";

      "The shared class does not work"
      ifvarclass => "!$(class_needed)";
}
