body file control
{
  namespace => "b";
}

bundle common variables
{
  vars:
      "array2[key]" string => "string2";
}

bundle agent test_in_namespace
{
  vars:
      "array_name2" string => "b:variables.array2";
      "repo_ids3" slist => getindices("$(array_name2)");

}

bundle agent check_in_namespace(test)
{
  methods:
      "any" usebundle => default:default_check_strcmp("$(b:test_in_namespace.repo_ids3)", "key", "$(test)", "no");
}

