#
# Test reading single-line list of packages
#

body common control
{
  inputs => { "../../default.cf", "107.cf.ext" };
  bundlesequence => { "g", default("$(this.promise_filename)") };
}


bundle agent init
{
vars:
  "dummy" string => "dummy";
}

#######################################################

bundle agent test
{
packages:
  "p"
    package_version => "",
    package_architectures => { "" },
    package_method => simplepkg("abug"),
    package_policy => "add",
    package_select => "==";
}


bundle agent check
{
vars:
  "dummy" string => "dummy";
}
