body file control
{
      namespace => "ns1";
}

bundle agent mytest(a)
{
  classes:
      "ns1global" expression => "any", scope => "namespace";

  vars:
    cfengine3::
      "ns1string" string => $(this.promise_dirname);

  files:
      "$(sys.workdir)/ppkeys/."
      create => "true";

  reports:
    EXTRA::
      "$(this.bundle): ns1string = '$(ns1string)'";
}

body file control
{
      namespace => "ns2";
}

bundle agent mytest(a,b)
{
  classes:
      "ns2global" expression => "cfengine3", scope => "namespace";

  vars:
      "ns2string" string => $(sys.fqhost);

  files:
      "$(sys.workdir)/ppkeys/."
      create => "true";

  reports:
    EXTRA::
      "$(this.bundle): ns2string = '$(ns2string)'";
}
