#######################################################
#
# mtime server copy, for non-localhost, should copy
#
#######################################################

body common control
{
      inputs => { "../../default.cf.sub" };
      bundlesequence  => { default("$(this.promise_filename)") };
      version => "1.0";
}

#######################################################

bundle agent init
{
}

#######################################################

bundle agent test
{
  files:

      "$(G.testdir)/destination_file" copy_from => copy_src_file,
      classes => if_repaired("repaired");
}

#########################################################

body copy_from copy_src_file

{
      source      => "$(G.testdir)/source_file";
      # localhost comes first but will be denied
      servers     => { @(sys.ip_addresses) };
      compare     => "mtime";
      copy_backup => "false";

      portnumber => "9878"; # lan_open

      #encrypt     => "true";
      #verify      => "true";
      #purge       => "false";
      #type_check  => "true";
      #force_ipv4  => "true";
      trustkey => "true";
}

#######################################################

bundle agent check
{
  classes:
      "dummy" expression => regextract("(.*)\.sub", $(this.promise_filename), "fn");

  methods:

      "any" usebundle => dcs_check_diff("$(G.testdir)/source_file","$(G.testdir)/destination_file","$(fn[1])");
}
