#######################################################
#
# mtime server copy, for non-localhost, no connect access, should not copy
#
#######################################################

body common control
{
      inputs => { "../../default.cf.sub" };
      bundlesequence  => { default("$(this.promise_filename)") };
      version => "1.0";
}

#######################################################

bundle agent init
{
}

#######################################################

bundle agent test
{
  files:

      "$(G.testdir)/destfile_classic"
          copy_from => copy_src_file("classic"),
          classes => if_repaired("copied_classic");
      "$(G.testdir)/destfile_latest"
          copy_from => copy_src_file("latest"),
          classes => if_repaired("copied_latest");
}

#########################################################

body copy_from copy_src_file(protocol_version)
{
      protocol_version => "$(protocol_version)";

      source      => "$(G.testdir)/source_file";
      # localhost comes first but will be denied
      servers     => { @(sys.ip_addresses) };
      compare     => "mtime";
      copy_backup => "false";

      portnumber => "9879"; # lan_deny_connect

      #encrypt     => "true";
      #verify      => "true";
      #purge       => "false";
      #type_check  => "true";
      #force_ipv4  => "true";
      trustkey => "true";
}

#######################################################

bundle agent check
{
  classes:
      "dummy" expression => regextract("(.*)\.sub", $(this.promise_filename), "fn");

  reports:

    !copied_classic.!copied_latest::
      "$(fn[1]) Pass";
    copied_classic|copied_latest::
      "$(fn[1]) FAIL";
}
