#######################################################
#
# Tries to copy using TLS (which is default now), from two servers: one
# with the default TLS ciphers list and another with a non-default very
# restricted one.
#
# It should fail since we are setting "tls_ciphers" to a cipher missing
# in both servers.
#
#######################################################

body common control
{
    inputs => { "../../default.cf.sub" };
    bundlesequence  => { default("$(this.promise_filename)") };
}

bundle agent init
{
}

bundle agent test
{
    files:
        "$(G.testdir)/missing_ok"
            classes => classes_generic("test"),
            copy_from       => dcs_remote_cp_X("does_not_exists", "localhost", "true");
}

bundle agent check
{
    classes:
        "dummy" expression => regextract("(.*)\.sub", $(this.promise_filename), "fn");
      
    reports:
        test_kept::
            "$(fn[1]) Pass";
        test_failed|test_repaired::
            "$(fn[1]) FAIL";
} 


body copy_from dcs_remote_cp_X(from,server, missing_ok)
# @brief Download a file from a remote server. They server is always trusted.
#
# @param from The location of the file on the remote server
# @param server The hostname or IP of the server from which to download
{
    servers     => { "$(server)" };
    source      => "$(G.testdir)/dir/$(from)";
    compare     => "mtime";
    trustkey    => "true";
    missing_ok  => "${missing_ok}";
    portnumber  => "9876"; # localhost_open
}
