# Deny localhost, admit other interface IPs

body common control
{
      bundlesequence => { "access_rules" };
      inputs => { "../../default.cf.sub" };

}

#########################################################
# Server config
#########################################################

body server control

{
      port => "9878";

      denyconnects          => { "127.0.0.1" };
      allowconnects         => { @(sys.ip_addresses) };
      allowallconnects      => { @(sys.ip_addresses) };
      trustkeysfrom         => { @(sys.ip_addresses) };
}

#########################################################

bundle server access_rules()

{
  access:

      "$(G.testdir)/source_file"     admit   => { @(sys.ip_addresses) };
}

