# In access_rules, deny "localhost" instead of "127.0.0.1"

body common control
{
      bundlesequence => { "access_rules" };
      inputs => { "../../default.cf.sub" };

}

#########################################################
# Server config
#########################################################

body server control

{
      port => "9887";

      allowconnects         => { "127.0.0.1" , "::1" };
      allowallconnects      => { "127.0.0.1" , "::1" };
      trustkeysfrom         => { "127.0.0.1" , "::1" };
      allowlegacyconnects   => { "127.0.0.1" , "::1" };
}

#########################################################

bundle server access_rules()

{
  access:
      "$(G.testdir)/source_file"
        admit   => { "0.0.0.0/0" },                                     # admit everyone but
        deny_hostnames    => { "localhost", "localhost.localdomain" };  # deny is stronger than admit
}

