
body common control
{
      bundlesequence => { "access_rules" };
      inputs => { "../../default.cf.sub" };

}

#########################################################
# Server config
#########################################################

body server control

{
      port => "9880";

      allowconnects         => { "127.0.0.1" , "::1" };
      allowallconnects      => { "127.0.0.1" , "::1" };
      trustkeysfrom         => { "127.0.0.1" , "::1" };
}

#########################################################

bundle server access_rules()

{
  access:

      # no access granted
}

