body common control
{
      bundlesequence => { "access_rules" };
      inputs => { "../../default.cf.sub" };

}

#########################################################
# Server config
#########################################################

body server control

{
      port => "9888";

      # Only this cipher is to be accepted
      allowciphers    => "AES128-GCM-SHA256";

      # Allow only TLSv1.1 or higher
      allowtlsversion => "1.1";

      allowconnects         => { "127.0.0.1" , "::1" };
      allowallconnects      => { "127.0.0.1" , "::1" };
      trustkeysfrom         => { "127.0.0.1" , "::1" };
}

#########################################################

bundle server access_rules()

{
  access:
      "$(G.testdir)/source_file"
        admit    => { "127.0.0.1", "::1" },
        shortcut => "simple_source";
}
