body common control
{
    inputs => { "../default.cf.sub" };
    bundlesequence  => { default("$(this.promise_filename)") };
    version => "1.0";
}

promise agent copy
{
    interpreter => "/usr/bin/python3";
    path => "$(this.promise_dirname)/copy.py";
}

bundle agent test
{
  meta:
    "description" -> { "CFE-3436" }
      string => "Test a custom promise with promise-specific log_level";

  copy:
    "$(G.testfile).dst"
      from => "$(G.testfile).src",
      log_level => "error";
}
