FROM ubuntu:22.04 AS build
RUN DEBIAN_FRONTEND=noninteractive apt-get update -y --fix-missing
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libssl-dev libxml2-dev libpam0g-dev liblmdb-dev libacl1-dev libpcre2-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3 git flex bison byacc automake make autoconf libtool valgrind curl
COPY masterfiles masterfiles
COPY core core
WORKDIR core
CMD bash tests/valgrind-check/run_checks.sh
