#######################################################
#
# mtime server copy, for non-localhost, no connect access, should not copy
#
#######################################################

body common control
{
      inputs => { "../../default.cf.sub" };
      bundlesequence  => { default("$(this.promise_filename)") };
      version => "1.0";
}

#######################################################

bundle agent init
{
}

#######################################################

bundle agent test
{
  files:

      "$(G.testdir)/destination_file"
      copy_from => copy_src_file,
      classes => if_repaired("repaired");
}

#########################################################

body copy_from copy_src_file

{
      source      => "$(G.testdir)/source_file";
      servers     => { @(sys.ip_addresses) }; # localhost is always granted
      compare     => "mtime";
      copy_backup => "false";

      portnumber => "9879"; # lan_deny_connect

      #encrypt     => "true";
      #verify      => "true";
      #purge       => "false";
      #type_check  => "true";
      #force_ipv4  => "true";
      trustkey => "true";
}

#######################################################

bundle agent check
{
  classes:
      "dummy" expression => regextract("(.*)\.sub", $(this.promise_filename), "fn");

  reports:

    !repaired::
      "$(fn[1]) Pass";
    repaired::
      "$(fn[1]) FAIL";
}
