#######################################################
#
# Test cf-serverd related promises, mtime simple copy localhost
#
# Tests secure copy (SGET) and secure stat (SSYNCH).
#
#######################################################

body common control
{
      inputs => { "../../default.cf.sub" };
      bundlesequence  => { default("$(this.promise_filename)") };
      version => "1.0";
}

#######################################################

bundle agent init
{
}

bundle agent test

{
  files:
      "$(G.testdir)/destination_file" copy_from => copy_src_file;
}

#########################################################

body copy_from copy_src_file

{
      source      => "$(G.testdir)/source_file";
      servers     => { "127.0.0.1" };
      compare     => "mtime";
      copy_backup => "false";

      portnumber => "9876"; # localhost_open

      encrypt     => "true";

      #verify      => "true";
      #purge       => "false";
      #type_check  => "true";
      #force_ipv4  => "true";
      trustkey => "true";
}

#######################################################

bundle agent check
{
  classes:
      "dummy" expression => regextract("(.*)\.sub", $(this.promise_filename), "fn");

  methods:
      "any" usebundle => dcs_check_diff("$(G.testdir)/source_file","$(G.testdir)/destination_file","$(fn[1])");
}
