
body common control
{
  bundlesequence => { "access_rules" };
  inputs => { "../../default.cf.sub" };

nova_edition::
  host_licenses_paid => "5";
}

#########################################################
# Server config
#########################################################

body server control 

{
port => "9878";

allowconnects         => { @(sys.ip_addresses) };
allowallconnects      => { @(sys.ip_addresses) };
trustkeysfrom         => { @(sys.ip_addresses) };
}

#########################################################

bundle server access_rules()

{
access:

  "$(G.testdir)/source_file"     admit   => { @(sys.ip_addresses) };
}

