
body common control
{
bundlesequence => { "access_rules" };
}

#######################################################

bundle common c
{
vars:

  "localhost_open"         string => "9876";
  "localhost_deny_connect" string => "9877";
  "lan_open"               string => "9878";
  "lan_deny_connect"       string => "9879";
  "localhost_noaccess"     string => "9880";
}

#########################################################
# Server config
#########################################################

body server control 

{
port => "$(c.lan_deny_connect)";

denyconnects          => { @(sys.ip_addresses) };
allowconnects         => { @(sys.ip_addresses) };
allowallconnects      => { @(sys.ip_addresses) };
trustkeysfrom         => { @(sys.ip_addresses) };
}

#########################################################

bundle server access_rules()

{
access:

  "/tmp/source_file"     admit   => { @(sys.ip_addresses) };
}

