body classes if_failed(x)
{
  repair_failed => { "$(x)" };
}

body contain run_under_shell
{
  useshell => "useshell";
}


bundle agent generate_key
{
commands:
  "$(sys.cf_key)";
}


bundle agent start_server(server_name)
{
vars:
  "cwd" string => dirname("$(this.promise_filename)");

commands:
  "$(sys.cf_serverd) -Kf $(cwd)/$(server_name).srv"
    classes => if_failed("server_failed");
}

# Use this to get the server messages in server-debug.log.
bundle agent start_server_debug(server_name)
{
vars:
  "cwd" string => dirname("$(this.promise_filename)");

commands:
  # Sleep 3 seconds since cf-serverd takes some time to start in debug mode.
  "$(sys.cf_serverd) -Kdf $(cwd)/$(server_name).srv >$(sys.workdir)/server-debug.log 2>&1 & sleep 3"
    contain => run_under_shell,
    classes => if_failed("server_failed");
}


bundle agent run_test(test_name)
{
commands:
  "$(sys.cf_agent) -Kf $(test_name) -D DEBUG,AUTO,ok";
}


bundle agent stop_server(server_name)
{
processes:
  "$(server_name)"
    signals => { "term", "kill" };
}
