#######################################################
#
# Test class creation with -D
#
#######################################################

body common control
{
  inputs => { "../../default.cf.sub" };
  bundlesequence  => { default("$(this.promise_filename)") };
  version => "1.0";
}

#######################################################

bundle agent init
{
vars:
        "dummy" string => "dummy";
}

#######################################################

bundle agent test
{
vars:
        "dummy" string => "dummy";
}

#######################################################

bundle agent check
{
classes:
    "dummy" expression => regextract("(.*)\.sub", $(this.promise_filename), "fn");

reports:
    DEBUG::
        "This should only pass if you do not run it with: -D ok";
        "Look at $(fn[1]) to see which flags are passed in";
    ok::
        "$(fn[1]) FAIL";
    !ok::
        "$(fn[1]) Pass";
}

