#######################################################
#
# Test initial class negation with -N
#
#######################################################

body common control
{
  inputs => { "../../default.cf.sub" };
  bundlesequence  => { default("$(this.promise_filename)") };   
  version => "1.0";
}

bundle agent init
{
vars:
	"dummy" string => "dummy";
}

#######################################################

bundle agent test
{
vars:
	"dummy" string => "dummy";
}

#######################################################

bundle agent check
{
classes:
    "ok" expression => "any";
    "dummy" expression => regextract("(.*)\.sub", $(this.promise_filename), "fn");

reports:
    DEBUG::
	"This should pass even if you run it with: -N ok";
	"Look at $(fn[1]) to see which flags are passed in";
    ok::
	"$(fn[1]) Pass";
    !ok::
	"$(fn[1]) FAIL";
}
