bundle agent __main__ {
  vars:
    any::
      "var1" string => "val1";
    def_var2::
      "var2" string => "val2";
    def_var3::
      "var3" string => "val3";
    def_var4::
      "var4" string => "val4";

  classes:
      "def_var2" expression => isvariable("var1");
      "def_var3" expression => isvariable("var2");
      "def_var4" expression => isvariable("var3");

  reports:
      "var1: $(var1)";
      "var2: $(var2)";
      "var3: $(var3)";
      "var4: $(var4)";
      "var5: $(var5)";
}
