\input texinfo-altfont
\input texinfo-logo
\input texinfo
@selectaltfont{cmbright}
@setlogo{NewLogo} 

@c *********************************************************************
@c
@c  This is a TEXINFO file. It generates both TEX documentation and
@c  the "on line" documentation "info" files.
@c
@c  The file is structured like a programming language. Each chapter
@c  starts with a chapter comment.
@c
@c  Menus list the subsections so that an online info-reader can parse
@c  the file hierarchically.
@c
@c ***********************************************************************
@c %** start of header
@setfilename cf-copernicus.info
@settitle Copernicus Hints
@setchapternewpage odd
@c %** end of header

@titlepage
@title Copernicus Hints
@subtitle A CFEngine AS reference
@author CFEngine AS

@c @smallbook


@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2008 CFEngine AS

@end titlepage


@c *************************** File begins here ************************

@ifnottex
@node Top, Introduction, (dir), (dir)
@top CFEngine-Reference
@end ifnottex

@ifinfo
@dircategory CFEngine Training
@direntry
* CFEngine Modularization:
                        CFEngine is a language based tool specifically
                        designed for configuring and maintaining
                        Unix-like operating systems attached
                        to a TCP/IP network.
@end direntry
@end ifinfo


@ifhtml
@html
<a href="#Contents"><h1>COMPLETE TABLE OF CONTENTS</h1></a>

<h2>Summary of contents</h2>

@end html
@end ifhtml

@c **********************************************************************
@c CHAPTER
@c **********************************************************************

@menu
* Introduction::                
* The content::                 
* Graphs::                      
* Improve Copernicus::          
@end menu

@node Introduction, The content, Top, Top
@chapter Introduction


Copernicus is CFEngine's knowledge integration tool, proving
semantically linked access to our extended documentation for support
customers. Copernicus is really just CFEngine 3 in disguise. The
website is powered by CFEngine 3's knowledge agent @code{cf-know}. Only
the content is proprietary -- and even then we encourage you to
help develop it by sending us suggestions for improvement.

Copernicus was made famous for his heliocentric view of the
universe, placing the sun at the centre and seeing the
planets orbit around it. 

@image{copernicus-planets,10cm,,The heliocentric solar system,png}

CFEngine's Copernicus is a simplified implentation of ISO standard
Topic Maps, in which every page is based around a topic. It places
a given topic of interest in the centre of focus and shows what other
concepts are closely related to it. Just click on a concept to see
how it relates to nearby concepts and to find references to the
documentation. 

The best way to use the topic map is simply to explore for a while
and use the search field to short-cut to relevant topics.

@itemize
@item Orange links point to concepts
@item Red links point to documents.
@end itemize

@c **********************************************************************
@c CHAPTER
@c **********************************************************************

@node The content, Graphs, Introduction, Top
@chapter The content

@menu
* Topics::                      
* Types::                       
* Associations::                
* Occurrences::                 
* Searching::                   
@end menu

@node Topics, Types, The content, The content
@section Topics

A topic is any subject that we want to talk about or represent.

Strictly speaking, the term <i>topic</i> refers to the object or node in
the topic map that represents the subject being referred to. However,
there is a one-to-one relationship between topics and
subjects, with every topic representing a single subject and every
subject being represented by just one topic. To a certain degree,
therefore, the two terms can be used interchangeably

@image{NewCopernicus,10cm,,A typical topic page,png}

@node Types, Associations, Topics, The content
@section Types

Topics can be categorized according to their type. In a topic map, any
given topic is an instance of zero or more topic types. This
corresponds to the categorization inherent in the use of multiple
indexes in a book (index of names, index of works, index of places,
etc.).

Types are used mainly to disambiguate topics of the same namin
different contexts.

@node Associations, Occurrences, Types, The content
@section Associations


An association is a semantic relationship between two topics.
The associative distance between topics is what defines the
solar system of a topic in Copernicus. Associations are what
links ideas together in the knowledge base, e.g.

@smallexample
is implemented by
is an example of
is an aspect/component of
was a feature added in
@end smallexample


@node Occurrences, Searching, Associations, The content
@section Occurrences

An occurrence of a topic is a piece of information about
it. This is normally the reason for using the topic map
in the first place -- to arrive at an actual document, or
occurrence of the topic. In CFEngine occurrences can be
short literal explanations, or the can be red URL pointers
to documentation.

An occurrence pointer will lead you some some text that
says something about the topic.

@node Searching,  , Occurrences, The content
@section Searching

The search field at the top right hand corner of the header may be
used to enter Perl Compatible Regular Expressions to match topic name
fragments. Searches are case insensitive. Do not enter more than one
keyword at a time, the expression should match only a single name,
e.g.

@smallexample
web
web server
web.*module.*
apache
@end smallexample

@c **********************************************************************
@c CHAPTER
@c **********************************************************************

@node Graphs, Improve Copernicus, The content, Top
@chapter Graphs

Copernicus provides some graphical representations of topic space,
showing approximately 30 of the closest related topics. This magic
number 30 is one of the Dunbar numbers and represents the number of
working relationships humans can typically maintain.

@image{NewCopernicusGraph,10cm,,A graphical view of related topics,png}


The graphics are not a complete represenation of the topic map but
are designed to provoke associative thought. You can reach all of
the links by going to the Associations section of a topic page (assuming
there are associations).

The graphical aspects of copernicus are being developed as part of our
research into knowledge management. Users can expect future
improvements to the analysis and navigation features.


@node Improve Copernicus,  , Graphs, Top
@chapter Improve Copernicus

Entering the expert knowledge in Copernicus is a huge and
time-consuming task.  Help us to improve the knowledge base by sending
us your wishes and suggestions. Every `stupid question' and smart
lateral thought that you send us can help someone to find what they
need more quickly.

We are constantly researching and analysing the data we have and
the patterns of usage we observe. All of this will lead to
a more sophisticated experience in the coming years.

@ifhtml
@html
<a name="Contents">
@end html
@end ifhtml

@contents

@ifhtml
@html
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2576171-2");
pageTracker._initData();
pageTracker._trackPageview();
</script>
@end html
@end ifhtml

@bye
