\input texinfo-altfont
\input texinfo-logo
\input texinfo
@selectaltfont{cmbright}
@setlogo{CFEngineFrontPage}
@c %** start of header
@setfilename cf-nova-gui.info
@settitle CFEngine Nova Mission Portal
@setchapternewpage odd
@c %** end of header
@titlepage
@title CFEngine Nova Mission Portal
@subtitle CFEngine Enterprise Documentation
@subtitle for version 2.1 beta1, 18. Aug 2011
@author CFEngine
@c @smallbook
@fonttextsize 10
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2011 CFEngine AS.
The features described herein are in provided for user convenience and imply no warranty whatsoever
to the extent of applicable law.
@end titlepage
@c *************************** File begins here ************************
@ifinfo
@dircategory CFEngine Training
@direntry
* CFEngine Reference:
                        CFEngine is a language based framework
                        designed for configuring and maintaining
                        Unix-like operating systems attached
                        to a TCP/IP network.
@end direntry
@end ifinfo
@ifnottex
@node Top
@top CFEngine Nova Mission Portal
@end ifnottex
@ifhtml
@html
<a href="#Contents"><h1>COMPLETE TABLE OF CONTENTS</h1></a>
<h2>Summary of contents</h2>
@end html
@end ifhtml

@iftex
@contents
@end iftex


@c *****************************************************
@c * CHAPTER
@c *****************************************************
@menu
* Introduction::
* Mission Portal::
@end menu

@node 
@chapter Introduction

CFEngine Nova is a commercially licensed version of the core CFEngine
software@footnote{Major version 3} with enterprise library extensions. All of
the documentation for CFEngine 3 applies to CFEngine Nova. This
document is a supplement describing the graphical user interphase used in CFEngine Nova: the Mission Portal.

Knowledge management has become a new focus in IT management, and it is a core focus at CFEngine.
Comprehending the growing complexity of IT operations is one of the main challenges in IT today.
CFEngine Nova has a number of key features for knowledge management, including automated documentation, report generation and associative inference. The CFEngine Mission Portal is the centerpiece
of user interaction with CFEngine Nova and can be accessed after the successful installation of the software on your hub server (policy host). Connect to the server (port 80) with your web browser (for example at http://123.456.789.123), you should see a login screen:

@sp 1
@center @image{img-login,5cm,,Mission Portal login}
@center Figure: Mission Portal login screen
@sp 1

@noindent Default user and password is 'admin' and 'admin' (make sure to change this at first login to prevent unauthorized access).

@c *****************************************************
@c * CHAPTER
@c *****************************************************
@node 
@chapter Mission Portal

@menu
* Mission Portal Rooms::
* Finders::
* Viewers::
* Editors::
* Settings::
@end menu

@image{img-mission-portal-nova-2-1,15cm,,Mission Portal}
@center Figure: The mission portal


@node 
@section Mission Portal Rooms

@menu
* Mission Status::
* Mission Engineering::
* Mission Planning::
* Mission Library::
@end menu

There are four main rooms in the Mission Portal that offer insight into different aspects of operations:

@itemize -
@item Mission status: a top level overview of compliance status and business value
@item Mission engineering: a place to see the current state of system repair
@item Mission planning: a place to plan and make policy changes
@item Mission library: a knowledge bank that connects information together
@end itemize

Each of these rooms is a beginning from which you can refine your overview and search
through information.

@page
@node 
@subsection Mission Status

Mission status is a high level summary of how well the entire system is behaving. 

@sp 1
@image{img-status,15cm,,Mission Status}
@center Figure: The status of IT operations.
@sp 1

Business Value and Host Status:
The two pie charts show the business value of the promises kept/not kept and well as host status, respectively. Business value is associated with the value of promises as defined in policy files. In the Host Status chart, each host represents a slice of the pie and is classified into red, yellow, green and blue according to the level of their compliance. A host is red if less than 80% of its promises are kept, yellow if 20% or more of its promises were repaired and host is now compliant, green if more than 80% of its promises are kept, and blue if there is no contact between the hub and the client host.

Compliance Summary:
The row of bar meters shows the compliance of all registered hosts @footnote{Blue hosts will not appear here} in blocks of 6 hours for the past week. It summarizes performance and anomalous behavior in a simple red (prommises not kept), yellow (promises repaired) and green (promises kept) scale. Click on a bar to see which promises were kept/not kept.

Services/Goals:
A summary of Mission goals (as defined in user policy files; these examples are from @file{company_knowledge.cf}). Edit the file in the policy editor (Planning room -> repository), or edit the file in your own text editor, to change these goals.


@page
@node
@subsection Mission Engineering

Mission engineering illustrates the state of the system in relation to the desired state at all scales. Zoom in to specific areas and examine the impact of promises, query data, and extract reports.

@sp 1
@image{img-engineering,15cm,,Mission Engineering}
@center Figure: Mission Engineering
@sp 1

@noindent Host Status:
@itemize -
@item The hosts are classified into red, yellow, green and blue according to the status of their compliance. A host is red if less than 80% of its promises are kept, yellow if 20% or more of its promises were repaired and host is now compliant, green if more than 80% of its promises are kept, and blue if there is no contact between the hub and the client. Clicking a link produces a list of the hosts in that category. 
@item Worst available host rank: Display the weakest hosts (that have been in contact with the hub) over the last hour.
@item Hub replication status: Display status of redundant monitoring hubs (if activated).
@end itemize

Promise compliance summary for all host(s):
The row of bar meters shows the compliance of all registered hosts over the past
week, the past day and the past hour. It also summarizes performance
and anomalous behavior in a simple red (promises not kept), yellow (promises repaired), and green (promises kept) scale.

Finders:
The Mission Engineering room comes with six finder functions (modules that make it simple and intuitive to browse and search for objects of a particular type, see section on Finders): host, class, promises, reports, summary reports, and CDP (Content Driven Policies) reports.


@page
@node
@subsection Mission Planning

Make changes to policies, goals determined by promises and implement specific tactics to achieve the desired state. Interact with data, approve changes and anomalies. Get an overiew of users logged on to the Mission Portal, as well as their current activity.

@sp 1
@image{img-planning,15cm,,Mission Planning}
@center Figure: Mission Planning
@sp 1

@noindent Policy Goals:
List of policy goals as defined in policy files; these examples are from @file{company_knowledge.cf}. Edit the file in the policy editor (Planning room -> repository) or edit the file in your own text editor. The "More..." button links  to the Service Catalogue, click to see which bundles contribute to these policy goals.

@noindent Action buttons:
@itemize -
@item Repository: Edit policy files in the integrated policy editor (requires Subversion)
@item Track records: Overview of promises repaired or not kept
@item Approve policies: To be developed
@item Service catalogue: See which bundles contribute to policy goals
@end itemize

@noindent Logged on:
Shows users currently logged on to the Mission Portal and their activity.

@noindent Activity log:
Shows the latest activity entries. Type in a new activity to keep colleagues posted on current work.


@page
@node
@subsection Mission Library

The Library contains finders for documents, topics, a notes archive, and (external) link to the CFEngine community.

@sp 1
@image{img-library,15cm,,Mission Library}
@center Figure: Mission Library
@sp 1

@noindent Library buttons:
@itemize -
@item Docs: Overview of documentation that was packaged with CFEngine Nova.
@item Find Topic: Search for topics either by scrolling through the alphabetical list or by typing in the search box (same as the search box on top right of page).
@item Notes Archive: Get overiew of all notes made in regard to hosts or reports.
@item Community: External link to the CFEngine community
@end itemize


@node
@section Finders

@menu
* Host finder::
* Class finder::
* Promise finder::
* Report finder::
* Summary report finder::
* Topic finder::
@end menu

Finders are modules that make it simple and intuitive to browse and search for objects of a particular type. Some are located in the Mission Engineering room, others in the Mission Library or the generic search box in the top right corner.

@sp 1
@center @image{img-finders,14cm,,Finders}
@center Figure: Finders in the Mission Engineering room
@sp 1


@page
@node
@subsection Host finder

The host finder is located in the Mission Engineering room and will display a list of hosts. Browse by scrolling through the list, click a letter corresponding to the first letter of a host name, or search for hosts in the search box (top right corner). Clicking on a host name will bring you to the host viewer.

@sp 1
@center @image{img-hostfinder,10cm,,Host finder}
@center Figure: Host finder
@sp 1

@node
@subsection Class finder

The class finder is located in the Mission Engineering room and will display a list of classes. Browse by scrolling through the list, click a letter corresponding to the first letter of a class name, or search for classes in the search box (top right corner; choose between searching all, time, soft or IP classes). Clicking on a class will bring you to a report for that class profile.

@sp 1
@center @image{img-classfinder,10cm,,Class finder}
@center Figure: Class finder.
@sp 1

@node
@subsection Promise finder

The promise finder is located in the Mission Engineering room and will display a list of promises. Browse by scrolling through the list, click a letter corresponding to the first letter of a promiser/bundle/handle name (set alternative in searchbox and click a letter in the right column), or search for promiser/bundle/handle in the search box (top right corner; choose between searching promiser, bundle, or handle). Clicking on a promise/bundle will bring you to the promise/bundle viewer.

@sp 1
@center @image{img-promisefinder,10cm,,Promise finder}
@center Figure: Promise finder
@sp 1

@node
@subsection Report finder

The report finder is located in the Mission Engineering room and will display a list of standard report categories. Browse by scrolling through the list. Clicking on a report category will bring up a query table that will produce a report according to the entered query criteria.

@sp 1
@center @image{img-reportsfinder,10cm,,Report finder}
@center Figure: Report finder
@sp 1

@noindent Standard reports:
@itemize -
    @item Bundle profile: Status of promise bundles and when they were last verified
    @item Business value report: Accumulated value of promises kept
    @item Class profile: User defined classes observed on the system
    @item Compliance by promise: Compliance of each promise individually
    @item Compliance summary: Total summary of host compliance
    @item File change log: Log of all detected changes to files from changes promises
    @item File change diffs: Delta/difference comparison showing file changes
    @item Last saw hosts: Log of when neighbouring hosts were last observed online
    @item Patches available: A list of patches currently claimed to be available by the local package manager
    @item Patch status: A list of (un)applied patches according to the local package manager
    @item Performance: Execution time used to verify selected promises
    @item Promises repaired log: Log of actual repairs made to the system
    @item Promises repaired summary: Cumulative (histogram) summary of promises repaired
    @item Promises not kept log: Log of promises that could not or would not be kept
    @item Promises not kept summary: Cumulative (histogram) summary of promises not kept
    @item Setuid/gid root programs: Current list of observed setuid/setgid root programs
    @item Software installed: List of software packages claimed to be installed according to the local package manager
    @item Variables: Table of variable values last observed
@end itemize


@node
@subsection Summary report finder

Find the current state of knowledge about promise compliance. Search by promise handle and/or host group (host class) and/or specific host. Click the @code{Help?} link to open the Promise finder or Classes finder to view available promise handles or host groups (host classes), respectively.

@sp 1
@center @image{img-summaryreportfinder,10cm,,Summary report finder}
@center Figure: Summary report finder
@sp 1

The result shows the number of hosts and their compliance when a single promise handle is specified, and an expectation value @footnote{Predicted mean in the time frame shown} of the number of hosts that match a search criteria when a search string (regex) is specified. Click @code{New search} to change or refine the query.

@sp 1
@center @image{img-summaryreport,15cm,,Summary report}
@center Figure: Summary report
@sp 1


@node
@subsection CDP report finder

A Content-Driven Policy (CDP) is a text file with lines containing semi-colon separated fields, like a spreadsheet or tabular file. Each line in the file is parsed and results in a specific type of promise being made, depending on which type the Content-Driven Policy is. The CDP report finder lists template CDPs that come with CFEngine Nova, click to view a report on the selected topic.

@sp 1
@center @image{img-cdpreportfinder,10cm,,CDP report finder}
@center Figure: CDP report finder
@sp 1


@node
@subsection Topic finder

The Topic finder is located in the Mission Library and will display a list of common topics. Browse by scrolling through the list, click a letter corresponding to the first letter of a topic name, or search for topics in the search box (top right corner). Clicking on a topic will bring you either to a document, web page or the Topic viewer (Knowledge map).

@sp 1
@center @image{img-topicsfinder,10cm,,Topic finder}
@center Figure: Topic finder
@sp 1


@page
@node
@section Viewers

@menu
* Host viewer::
* Bundle viewer::
* Promise viewer::
* Vital signs viewer::
* Topics viewer (Knowledge map)::
* Weakest hosts viewer::
* Report viewer::
@end menu

Viewers show info about the main objects at different scales of the system.

@node
@subsection Host viewer

Shows information about hosts, including name, status, operating system, vital signs, promises not kept, standard and custom reports, and more. View and make notes about the host.

@sp 1
@center @image{img-hostviewer,15cm,,Host viewer}
@center Figure: Host viewer
@sp 1

@noindent Action buttons:
@itemize -
@item Reports: Tabular summary of the host's internal information, tailored to a particular topics
@item Notes: View and make comments about this host
@item Vitals: Overview of monitoring data for this host and its current performance statistics
@item Problems: Overview of promises not kept by this host
@end itemize

@noindent Monitored jobs:
To be developed.

@noindent Analysis: The bar meter shows the host-summary status of a number of key
performance indicators.

@itemize -
@item Week: The average level of promise-compliance over the whole past week.
@item Day:  The average level of promise-compliance over the past day.
@item Hour:  The average level of promise-compliance over the past hour.
@item Perf: The average performance status of the system, compared to the learned norm.
@item Chng: Software update status of the system (only shows on hub, not displayed on clients).
@item Seen: The average level of connectivity compliance (to the hub) over the past week .
@item Anom: Level of anomalous site-wide activity on the system.
@end itemize


@node
@subsection Bundle viewer

The bundle viewer provides an interface to explore the context (class) in which a bundle is used and the promises made within that bundle. Tabs display other bundles using the one currently viewed and a general overview of all bundles. Navigate to interact with other views and get a complete picture of context, leads, references, affected objects, similar topics, and more.

@sp 1
@center @image{img-bundleviewer,15cm,,Bundle viewer}
@center Figure: Bundle viewer
@sp 1


@page
@node
@subsection Promise viewer

The promise viewer shows a promise definition and body. There are tabs for viewing leads (promise type, context, dependencies), other promises used in same bundle, other promises made by same promiser, and other promises of same type.

@sp 1
@center @image{img-promiseviewer,15cm,,Promise viewer}
@center Figure: Promise viewer
@sp 1

@page
@node
@subsection Vital signs viewer

The Vital signs viewer shows an
overview of monitoring data from each host and its current performance
statistics. In order to see data in these graphs, each host in the CFEngine
managed network must be running @code{cf-monitord} and @code{cf-serverd}.
This is the default behavior for a Nova installation.

@sp 1
@center @image{img-vitalsviewer,15cm,,Vital signs viewer}
@center Figure: Vital signs viewer
@sp 1

@node
@subsection Topics viewer (Knowledge map)

The Topics viewer, or Knowledge map, is a @i{sematic web} of subject references and document pointers. In a semantic web, you are presented with links to
documents about your chosen topic, as usual; in addition you are
offered @i{leads} and possible pathways to topics that are known to be
related. These leads don't just point you to more documents, but
explain @i{how} neighboring issues are related.  The aim is to help
the user learn from the experience of browsing, by conveying the
meaning of the current topic in relation to other issues in the
system. This is how @i{knowledge transfer} occurs.

The Knowledge Map can be found by searching for a topic in the top right corner or through the topic finder in the Mission Library (this will sometimes also lead directly to a document or web page instead).

@sp 1
@center @image{img-topicsviewer,15cm,,Topics viewer}
@center Figure: Topics viewer (Knowledge map)
@sp 1

The yellow sphere represents the current topic, surrounding (blue) spheres represent related topics, and the size of the spheres represents the number of associations each topic has. This map is navigable: click on a different topic to see a new view centered on that topic and its associations. The tabs will show leads, references, topics in the same context, and sub topics in the same context. Links can also lead to other viewers in the Mission Portal, documents and web pages related to the current topic.

@node
@subsection Weakest hosts viewer

A link to the worst ranked hosts is located in the Mission Engineering room. This ranks all hosts that have reported to the hub @footnote{Blue hosts will not appear} according to their level of promises not kept during the last hour, with the worst host on top.

@sp 1
@center @image{img-weakesthostsviewer,15cm,,Weakest hosts}
@center Figure: Weakest hosts
@sp 1

@node
@subsection Report viewer

A significant capability of CFEngine Nova is the existence of automated system reporting. A report is a tabular summary of CFEngine's internal information, tailored to a particular purpose. Reports describe
attributes and qualities of managed hosts and can be filtered through the text boxes on top of each column.

@sp 1
@center @image{img-reportviewer,15cm,,Report viewer}
@center Figure: Report viewer
@sp 1

Reports are updated at different intervals, the default values are every 5 minutes or 6 every hours (this can be changed by the user). Below is a list of standard reports, updated every 5 minutes unless otherwise noted:
@itemize -
     @item Bundle profile: Status of promise bundles and when they were last verified
     @item Business value report: Accumulated value of promises kept (6 hrs)
     @item Class profile: User defined classes observed on the system
     @item Compliance by promise: Compliance of each promise individually
     @item Compliance summary: Total summary of host compliance
     @item File change log: Log of all detected changes to files from changes promises
     @item File change diffs: Delta/difference comparison showing file changes
     @item Last saw hosts: Log of when neighbouring hosts were last observed online
     @item Patches available: A list of patches currently claimed to be available by the local package  manager (6 hrs)
     @item Patch status: A list of (un)applied patches according to the local package manager (6 hrs)
     @item Performance: Execution time used to verify selected promises
     @item Promises repaired log: Log of actual repairs made to the system
     @item Promises repaired summary: Cumulative (histogram) summary of promises repaired
     @item Promises not kept log: Log of promises that could not or would not be kept
     @item Promises not kept summary: Cumulative (histogram) summary of promises not kept
     @item Setuid/gid root programs: Current list of observed setuid/setgid root programs (6 hrs)
     @item Software installed: List of software packages claimed to be installed according to the local package manager (6 hrs)
     @item Variables: Table of variable values last observed (6 hrs)
@end itemize


@node
@section Editors

@menu
* Policy editor::
@end menu

The policy editor works with a subversion repository, the Mission Portal will prompt you for the path and login credentials. Setup of a subversion repository has to be done separately.

@node
@subsection Policy editor

The CFEngine Nova Mission Portal provides an editor for working on
CFEngine language. The editor provides syntax high-lighting and look-up to make working
with CFEngine's extensive language easier.

The main key commands in the editor Window are:

@table @i
@item Autocompletion: Ctrl+Space 
Shows a pop-up menu of possible items. This is context sensitive,
e.g. it also works inside lists (e.g. @code{bsdflags}) to provide
possible values.
@item Undo: Ctrl+Z 
 In Safari, Ctrl-backspace may be used.
@item Redo: Ctrl+Y
Undo an undo operation, i.e. reverse the direction of transaction roll.
@item Indent: TAB
Format a file to a standard indentation.
@end table

Multiple documents appear as tabs along the top of the screen.
@sp 1
@center @image{img-policy-editor,15cm,,Policy Editor}
@center Figure: The Policy Editor
@sp 1

The CFEngine Nova policy editor detects syntax errors and highlights
these in red to avoid mistakes when editing.  In addition, by using
the @code{Check syntax} button, it is possible to pre-test the policy
before committing changes to a repository. This will run
@code{promises.cf} through the @code{cf-promises} parser.

The main menu on the left hand panel shows the main workflow items for
policy editing. Clicking the arrow in the panel divider collapses the
menu and gives full-screen editing.

The right hand panel shows basic file and Subversion commands. The @code{Save} button will store a local/version of the opened files without committing to the repository. 


@node 
@section Mission Portal Settings

@menu
* Mission Portal Configuration::
* Mission Portal User Admin::
@end menu


@node 
@subsection Mission Portal Configuration

Configure and view various settings for the Mission Portal.

@sp 1
@image{img-settings,15cm,,Mission Portal Settings}
@center Figure: Mission Portal Settings
@sp 1

@itemize -
@item List of saved searches: View saved searches (e.g. searches saved from reports viewer/finder)
@item Mission Portal settings: Configure access authentication mode (database, LDAP, Active Directory)
@item My preferences: Turn tooltips on/off and enter default number of rows to be shown in reports
@end itemize


@node 
@subsection Mission Portal User Admin

Manage users and groups for the Mission Portal.

@sp 1
@image{img-useradmin,15cm,,Mission Portal User Admin}
@center Figure: Mission Portal User Admin
@sp 1

@node
@appendix Configuration of LDAP

LDAP authentication is available for CFEngine Nova 2.1 and up, but by default the mission portal will use the embedded database to store user information (default username and password are "admin" and "admin"). Note that users in the default database will be locked out of the Mission Portal upon configuration of LDAP. They will regain access if LDAP authentication is deactivated by selecting the Database button on the Mission Portal Settings page (see below).

To enable LDAP on a fresh install, log on to the Mission Portal with the default user and password and go to "Settings". Click "Mission Portal Settings" and enter the appropriate configuration for LDAP or Active Directory as described below.


@node
@section Configure LDAP

Select the LDAP button and enter the appropriate configuration settings for your system.

@sp 1
@center @image{img-configldap,15cm,,Configure LDAP}
@center Figure: Configure LDAP
@sp 1

@noindent Form fields:

@itemize -
@item LDAP host: Address of the LDAP machine
@item Base dn: LDAP root, the top entry (starting point) in the directory
@item Login attribute: Field name used to match username, e.g. uid.
@item User directory: Directory name where usernames are stored, e.g. cn=users or ou=people
@item Member attribute: Field name used to match user group (only needed for OPENLDAP), e.g. memberUid
@end itemize

Always check that the entered configuration is correct by clicking the "Test it" button before submitting changes. Enter a valid username and password in the popup to test LDAP bind. Submitting an incorrect configuration will put LDAP down and lock out all users, CFE Nova therefore comes with a fallback solution. It will look for a fallback administrator group in the database, select this from the dropbox.

Also select which user group will have general administrator privileges in the Mission Portal. This group will be able to access the Mission Portal settings and configuration tools.

@node
@section Configure Active Directory

Select the Active Directory button.

@sp 1
@center @image{img-configactivedirectory,15cm,,Configure Active Directory}
@center Figure: Configure Active Directory
@sp 1

@noindent Form fields:

@itemize -
@item LDAP host: Address of the LDAP machine
@item Base dn: LDAP root, the top entry (starting point) in the directory
@item Login attribute: Field name used to match username, e.g. uid.
@item User directory: Directory name where usernames are stored, e.g. cn=users or ou=people
@item Active directory domain: Field name used to match directory domain on Windows machines, e.g. windows1.test.cfengine.com
@end itemize

Always check that the entered configuration is correct by clicking the "Test it" button before submitting changes. Enter a valid username and password in the popup to test LDAP bind. Submitting an incorrect configuration will put LDAP down and lock out all users, CFE Nova therefore comes with a fallback solution. It will look for a fallback administrator group in the database, select this from the dropbox.

Also select which user group will have general administrator privileges in the Mission Portal. This group will be able to access the Mission Portal settings and configuration tools.



@c =========================================================================
@c @node Index,  , CFEngine Methods, Top
@c @unnumbered Concept Index
@c @printindex cp
@c =========================================================================
@ifhtml
@html
<a name="Contents">
@contents
@end html
@end ifhtml

@c  The file is structured like a programming language. Each chapter
@c  starts with a chapter comment.
@c
@c  Menus list the subsections so that an online info-reader can parse
@c  the file hierarchically.
@ifhtml
@html
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2576171-2");
pageTracker._initData();
pageTracker._trackPageview();
</script>
@end html
@end ifhtml
@bye
