\input texinfo-altfont
\input texinfo-logo
\input texinfo
@selectaltfont{cmbright}
@setlogo{CFEngineFrontPage}
@c *********************************************************************
@c
@c  This is a TEXINFO file. It generates both TEX documentation and
@c  the "on line" documentation "info" files.
@c
@c  The file is structured like a programming language. Each chapter
@c  starts with a chapter comment.
@c
@c  Menus list the subsections so that an online info-reader can parse
@c  the file hierarchically.
@c
@c ***********************************************************************@c 
@c %** start of header
@setfilename NovaGetStarted.info
@settitle Get Started Guide for CFEngine 3 Nova
@c @setchapternewpage odd
@c %** end of header
@titlepage
@title Get Started Guide for CFEngine 3 Nova
@subtitle CFEngine Enterprise Documentation
@subtitle Updated 21. October 2011
@author CFEngine
@c @smallbook
@fonttextsize 10
@c @page
@vskip 0pt plus 1fill
Copyright @copyright{} 2011 CFEngine AS.
The features described herein are in provided for user convenience and imply no warranty whatsoever
to the extent of applicable law.
@end titlepage
@c *************************** File begins here ************************
@ifinfo
@dircategory CFEngine Training
@direntry
* CFEngine Reference:
                        CFEngine is a language based framework
                        designed for configuring and maintaining
                        Unix-like operating systems attached
                        to a TCP/IP network.
@end direntry
@end ifinfo
@ifnottex
@node Top, , (dir), (dir)
@top Igniting CFEngine 3 Nova!
@end ifnottex
@ifhtml
@html
<a href="#Contents"><h1>COMPLETE TABLE OF CONTENTS</h1></a>
<h2>Summary of contents</h2>
@end html
@end ifhtml

@iftex
@contents
@end iftex


@menu
* Installing CFEngine 3 Nova::  
* Mission Portal::
* Next steps::  
@end menu


@c *****************************************************
@c * CHAPTER
@c *****************************************************
@node Installing CFEngine 3 Nova, Mission Portal, Top, Top
@chapter Installing CFEngine 3 Nova

@menu
* Installation procedure::      
@end menu

@node Installation procedure, , Installing CFEngine 3 Nova, Installing CFEngine 3 Nova
@section Installation procedure

CFEngine 3 Nova is designed to be simple to install in its default configuration. The installation
process has three phases:

@itemize
@item Unpacking the software.
@item Obtaining a license.
@item Adapting policy.
@end itemize

For Windows related issues, see our special topic guide @url{http://cfengine.com/manuals/st-windows.html}.

You should start from a blank system. If you have been using CFEngine Community Edition and you have
already developed a policy, set aside this policy during the installation process. You will be able
to integrate it back later.

Nova is provided in two packages, @file{cfengine-nova} and @file{cfengine-nova-expansion}. The main software package 
must be installed on every host (including the hub). The expansion package is only installed on the policy hub. You should install and set up the hub first.

@enumerate
@item Verify that the machine's network connection is working. On the hub, verify that package managers @code{yum},
@code{zypper} or @code{apt-get} are working (e.g. @code{apt-get update}).

@item Copy the Nova packages to the system. On the hub (policy server):
@example
cfengine-nova_2.1.@var{xxx.[rpm|deb]}
cfengine-nova-expansion_2.1.@var{xxx.[rpm|deb]}
@end example
@noindent On all other machines:
@example
cfengine-nova_2.1.@var{xxx.[rpm|deb]}
@end example

@item Unpack the software:
@table @i
@item Red Hat family
@example
host# rpm -ihv @var{packages}
@end example

@item SUSE family
@example
host# rpm -ihv @var{packages}
@end example

@item Debian family
@example
host# dpkg --install  @var{packages}
@end example

@end table 

@item On the hub, a public key has now been created in @file{/var/cfengine/ppkeys/localhost.pub} as part of the
package installation. You should send this public key to CFEngine Support@footnote{You will obtain credentials to the CFEngine Support ticketing system and software download repository as a part of your purchase.} as an attachment in the ticket system, 
to obtain a license file @file{license.dat}. 

@cartouche
Save the returned license file to @file{/var/cfengine/masterfiles/license.dat} 
on the hub before continuing.
@end cartouche


@item The remaining steps apply to all hosts, but you should install the hub or policy server first. For large systems (> 1000 hosts) we recommend increasing the memory limit in php.ini on the hub (for instance to 128 MB).

Find the hostname or IP address of the hub (policy server), here we assume @samp{123.456.789.123} is the address.
@verbatim
 hub # /var/cfengine/bin/cf-agent --bootstrap --policy-server 123.456.789.123
@end verbatim
Use the same command on all hosts, i.e. *** do not bootstrap the policy server with a localhost address *** 
If you mistype the address of the hub, we recommend doing the following steps to re-boostrap.
@verbatim
 hub # /var/cfengine/bin/cf-agent --bootstrap --policy-server 123.456.789.124
 hub # killall cf-execd cf-serverd cf-monitord cf-hub
 hub # rm -rf /var/cfengine/inputs/*
 hub # rm -f /var/cfengine/policy_server.dat
 hub # /var/cfengine/bin/cf-agent --bootstrap --policy-server 123.456.789.123
@end verbatim

CFEngine will output diagnostic information upon bootstrap. Error messages will be displayed if bootstrapping failed, pursue these to get an indication of what went wrong and correct accordingly. If all is well you should see the following in the output:

@verbatim

-> Bootstrap to 123.456.789.123 completed successfully

@end verbatim

@item CFEngine should now be up and running on your system. It will copy its default policy files into @file{masterfiles} on the hub (policy server). When the clients are bootstrapped, they will contact the hub and copy them to their @file{inputs} directory.

@item To complete licensing setup, you should make a promise to accept the license
terms by editing @file{/var/cfengine/masterfiles/promises.cf}
on the hub (policy server), changing the line @samp{host_licenses_paid => "<NUMBER>";}
in @samp{body common control} to reflect the correct number of licenses that you have subscribed to.

@end enumerate

@noindent @b{How to assess success in this procedure:}

@enumerate

@item Look at the process list on the systems with @samp{ps waux | grep cf-}.
You should be able to see @code{cf-execd} running, and eventually other processes from 
the CFEngine suite like @code{cf-monitord} @code{cf-serverd}. On the hub, you should 
also eventually see @code{cf-hub}. Note that it may take 5--10 minutes before all the
processes get started.

@item Look for files in @file{/var/cfengine/inputs} (Unix)
or @file{C:\Program Files\Cfengine\inputs} (Windows). The license
file will be copied out from the policy server to the clients as part
of the normal distribution of policy. Each machine should get a
copy of the @file{license.dat} file in @file{/var/cfengine/inputs}
(Unix) or @file{C:\Program Files\Cfengine\inputs} (Windows).

@item On the hub, the file @file{/var/cfengine/promise_knowledge.cf} should have been
created, and should contain data.

@item  Finally, try to connect to the web server at port 80 on the hub/policy host (for example at http://123.456.789.123).
You should see a login page like the one shown in the figure below:

@sp 1
@center @image{img-login,5cm,,Mission Portal login}
@center Figure: Mission Portal login screen
@sp 1
@end enumerate

Default user name and password is 'admin' and 'admin' (make sure to change this at first login to prevent unauthorized access).

Note that some of the displays in the Mission Portal may be blank when you log in just after installation; some reports and graphs are only updated every six hours. It may also take some time for the system to fully converge, do not get troubled if initially there are some promises repaired or not kept.

Please refer to the CFEngine 3 Nova Owner's Manual @*
(@url{http://www.cfengine.com/manuals/Enterprise-2-2-OwnersManual.html}) for complete information and help troubleshooting your installation.


@c *****************************************************
@c * CHAPTER
@c *****************************************************
@node  Mission Portal, Next steps, Installing CFEngine 3 Nova, Top
@chapter Mission Portal

@menu
* Mission Portal Rooms::        
@end menu

The Mission Portal is the centerpiece
of user interaction with CFEngine 3 Nova. It can be accessed by connecting to the hub (policy server) with your web browser (for example at http://123.456.789.123; default port 80). From here you can get a complete overview of operations and performance, business and compliance, organizational knowledge and library. We will make a quick introduction of the four main rooms in the Mission Portal, please refer to the CFEngine 3 Nova Owner's Manual for a complete overview: @url{http://www.cfengine.com/manuals/Enterprise-2-2-OwnersManual.html}

@image{img-missionportal,15cm,,Mission Portal}
@center Figure: The mission portal


@c *****COPY BELOW FROM cf3-nova-mission-portal.texinfo*******
@node  Mission Portal Rooms, Mission Status, Mission Portal, Mission Portal
@section Mission Portal Rooms

@menu
* Mission Status::              
* Mission Engineering::         
* Mission Planning::            
* Mission Library::             
@end menu

There are four main rooms in the Mission Portal that offer insight into different aspects of operations:

@itemize -
@item Mission status: a top level overview of compliance status and business value
@item Mission engineering: a place to see the current state of system repair
@item Mission planning: a place to plan and make policy changes
@item Mission library: a knowledge bank that connects information together
@end itemize

Each of these rooms is a beginning from which you can refine your overview and search
through information.

@page
@node  Mission Status, Mission Engineering, Mission Portal Rooms, Mission Portal Rooms
@subsection Mission Status

Mission status is a high level summary of how well the entire system is behaving. 

@sp 1
@image{img-status,15cm,,Mission Status}
@center Figure: The status of IT operations.
@sp 1

Business Value and Host Status:
The two pie charts show the business value of the promises kept/not kept and well as host status, respectively. Business value is associated with the value of promises as defined in policy files. In the Host Status chart, each host represents a slice of the pie and is classified into red, yellow, green and blue according to the level of their compliance. A host is red if less than 80% of its promises are kept, yellow if 20% or more of its promises were repaired and host is now compliant, green if more than 80% of its promises are kept, and blue if there is no contact between the hub and the client host.

Compliance Summary:
The row of bar meters shows the compliance (average percentage of promises kept, repaired or not kept) of all registered hosts @footnote{Blue hosts will not appear here} in blocks of 6 hours for the past week. It summarizes performance and anomalous behavior in a simple red (promises not kept), yellow (promises repaired) and green (promises kept) scale. Click on a bar to see which promises were kept/not kept.

Services/Goals:
A summary of Mission goals (as defined in user policy files). See the CFEngine 3 Nova Owners Manual for more information.


@page
@node Mission Engineering, Mission Planning, Mission Status, Mission Portal Rooms
@subsection Mission Engineering

Mission engineering illustrates the state of the system in relation to the desired state at all scales. Zoom in to specific areas and examine the impact of promises, query data, and extract reports.

@sp 1
@image{img-engineering,15cm,,Mission Engineering}
@center Figure: Mission Engineering
@sp 1

@noindent Host Status:
@itemize -
@item The hosts are classified into red, yellow, green and blue according to the status of their compliance. A host is red if less than 80% of its promises are kept (> 20% not compliant), yellow if 20% or more of its promises were repaired and host is now compliant (> 20% repaired, now compliant), green if more than 80% of its promises are kept (> 80% compliant), and blue if there is no contact between the hub and the client (host unreachable). Clicking a link produces a list of the hosts in that category.
@item Worst available host rank: Display the weakest hosts (that have been in contact with the hub) over the last hour.
@item Hub replication status: Display status of redundant monitoring hubs (if activated).
@end itemize

@noindent Promise compliance summary for reachable hosts:@*
The row of bar meters shows the compliance (average percentage of promises kept, repaired or not kept) of all registered hosts over the past week, the past day and the past hour. It summarizes performance
and anomalous behavior in a simple red (promises not kept), yellow (promises repaired), and green (promises kept) scale. The "Chng" bar relates to the amount of changes made to files monitored by a CFEngine policy in the last hour (change watch). It is green if no changes have been made. The level of yellow increases as changes occur (but it will never be red).  For the "Seen" bar, CFEngine monitors connections to the clients and reports a yellow or red status according to the length of time since it was in touch with one of the managed clients. The "Anom" bar relates to anomalies and is generated from monitoring data (vitals) for the last week. 

Finders:
The Mission Engineering room comes with six finder functions (modules that make it simple and intuitive to browse and search for objects of a particular type): host, class, promises, reports, summary reports, and CDP (Content Driven Policies) reports. See CFEngine Owner's Manual for more information.


@page
@node Mission Planning, Mission Library, Mission Engineering, Mission Portal Rooms
@subsection Mission Planning

Make changes to policies, goals determined by promises and implement specific tactics to achieve the desired state. Interact with data, approve changes and anomalies. Get an overview of users logged on to the Mission Portal, as well as their current activity.

@sp 1
@image{img-planning,15cm,,Mission Planning}
@center Figure: Mission Planning
@sp 1

@noindent Policy Goals:
List of policy goals as defined in policy files; these examples are from @file{company_knowledge.cf}. Edit the file in the policy editor (Planning room -> repository) or edit the file in your own text editor. The "More..." button links  to the Service Catalogue, click to see which bundles contribute to these policy goals.

@noindent Action buttons:
@itemize -
@item Repository: Edit policy files in the integrated policy editor (requires Subversion)
@item Track records: Overview of promises repaired or not kept
@item Approve policies: Give your approval of a submitted policy file
@item Service catalogue: See which bundles contribute to policy goals
@end itemize

@noindent Logged on:
Shows users currently logged on to the Mission Portal and their activity.

@noindent Activity log:
Shows the latest activity entries. Type in a new activity to keep colleagues posted on current work.


@page
@node Mission Library, Topics viewer (Knowledge map), Mission Planning, Mission Portal Rooms
@subsection Mission Library

@menu
* Topics viewer (Knowledge map)::
@end menu
The Library contains finders for documents, topics, a notes archive, and (external) link to the CFEngine community.

@sp 1
@image{img-library,15cm,,Mission Library}
@center Figure: Mission Library
@sp 1

@noindent Library buttons:
@itemize -
@item Docs: Overview of documentation that was packaged with CFEngine 3 Nova.
@item Find Topic: Search for topics either by scrolling through the alphabetical list or by typing in the search box (same as the search box on top right of page).
@item Notes Archive: Get overview of all notes made in regard to hosts or reports.
@item Community: External link to the CFEngine community
@end itemize


@node Topics viewer (Knowledge map), , Mission Library, Mission Library
@subsubsection Topics viewer (Knowledge map)

The Topics viewer, or Knowledge map, is a @i{sematic web} of subject references and document pointers. In a semantic web, you are presented with links to
documents about your chosen topic. In addition you are
offered @i{leads} and possible pathways to topics that are known to be
related. These leads don't just point you to more documents, but
explain @i{how} neighboring issues are related.  The aim is to help
the user learn from the experience of browsing, by conveying the
meaning of the current topic in relation to other issues in the
system. This is how @i{knowledge transfer} occurs.

The Knowledge Map can be found by searching for a topic in the top right corner or through the topic finder in the Mission Library (this will sometimes also lead directly to a document or web page instead).

@sp 1
@center @image{img-topicsviewer,15cm,,Topics viewer}
@center Figure: Topics viewer (Knowledge map)
@sp 1

The yellow sphere represents the current topic, surrounding (blue) spheres represent related topics, and the size of the spheres represents the number of associations each topic has. This map is navigable: click on a different topic to see a new view centered on that topic and its associations. The tabs will show leads, references, topics in the same context, and sub topics in the same context. Links can also lead to other viewers in the Mission Portal, documents and web pages related to the current topic.

@c *****************************************************
@c * CHAPTER
@c *****************************************************
@node Next steps, , Mission Portal, Top
@chapter Next steps

Please refer to the CFEngine 3 Nova Owner's Manual for complete information about this product. You may also wish to visit our getting started section on cfengine.com:

@itemize
@item @url{http://cfengine.com/manuals/Enterprise-2-2-OwnersManual.html}
@item @url{http://cfengine.com/getting-started}
@end itemize

@c =========================================================================
@c @node Index,  , CFEngine Methods, Top
@c @unnumbered Concept Index
@c @printindex cp
@c =========================================================================
@ifhtml
@html
<a name="Contents">
@contents
@end html
@end ifhtml

@c  The file is structured like a programming language. Each chapter
@c  starts with a chapter comment.
@c
@c  Menus list the subsections so that an online info-reader can parse
@c  the file hierarchically.
@ifhtml
@html
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2576171-2");
pageTracker._initData();
pageTracker._trackPageview();
</script>
@end html
@end ifhtml
@bye
