\input texinfo-altfont
\input texinfo-logo
\input texinfo
@selectaltfont{cmbright}
@setlogo{CFEngineFrontPage}

@c *********************************************************************
@c
@c  This is a TEXINFO file. It generates both TEX documentation and
@c  the "on line" documentation "info" files.
@c
@c  The file is structured like a programming language. Each chapter
@c  starts with a chapter comment.
@c
@c  Menus list the subsections so that an online info-reader can parse
@c  the file hierarchically.
@c
@c ***********************************************************************
@c %** start of header
@setfilename st-adopt.info
@settitle Adopting Cfengine in Your Organization
@setchapternewpage odd
@c %** end of header

@titlepage
@title Adopting CFEngine in Your Organization
@subtitle A CFEngine Special Topics Handbook
@author CFEngine AS


@page

@cartouche
@quotation
CFEngine is a framework and a methodology with far reaching
implications for the way you do IT management. The CFEngine approach
asks you to think in terms of @i{promises} and @i{cooperation} between
parts; it automates repair and maintenance processes and provides
simple integrated Knowledge Management.

@end quotation
@end cartouche

@vskip 0pt plus 1filll
Copyright @copyright{} 2009 CFEngine AS

@end titlepage


@c *************************** File begins here ************************


@ifinfo
@dircategory CFEngine Training
@direntry
* CFEngine Modularization:
                      CFEngine is a language based tool specifically
                      designed for configuring and maintaining
                      Unix-like operating systems attached
                      to a TCP/IP network.
@end direntry
@end ifinfo

@ifnottex
@node Top, What does adoption involve?, (dir), (dir)
@top Adoption
@menu
* What does adoption involve?::  
* The Mission Plan::            
* Commercial or Free?::         
* Installation or Pilot::       
* Identifying the Team::        
* Training and Certification::  
* Mission Goal and Knowledge Management::  
* Build::                       
* Contact CFEngine::            
@end menu

@end ifnottex
@iftex
@contents
@end iftex

@ifhtml
@html
<a href="#Contents"><h1>COMPLETE TABLE OF CONTENTS</h1></a>
<h2>Summary of contents</h2>
@end html
@end ifhtml

@node What does adoption involve?, The Mission Plan, Top, Top
@unnumberedsec What does adoption involve?
@sp 1

CFEngine is a framework and a methodology with far reaching
implications for the way you do IT management. The CFEngine approach
asks you to think in terms of @i{promises} and @i{cooperation} between
parts; it automates repair and maintenance processes and provides
simple integrated Knowledge Management.

To use CFEngine effectively, you should spend a little time learning
about the approach to management, as this will save you a lot of time
and effort in the long run.

@node The Mission Plan, Commercial or Free?, What does adoption involve?, Top
@unnumberedsec The Mission Plan
@sp 1

At CFEngine, we refer to the management of your datacentre as `The
Mission'. The diagram below shows the main steps in preparing mission
control. Some training is recommended, and as much planning as you can
manage in advance. Once a mission is underway, you should expect to
work by making small corrections to the mission plan, rather than
large risky changes.

@center @image{MissionPlan,10cm,,Mission Plan,.pdf}

Planning does not mean sitting around a table, or in front of a whiteboard.
Successful planning is a dialogue between theory and practice. It should include
test pilots and proof-of-concept implementations.

@node Commercial or Free?, Installation or Pilot, The Mission Plan, Top
@unnumberedsec Commercial or Free?
@sp 1

The first decision you should make is whether you will choose a route
of commercial assistance or manage entirely on your own. You can
choose different levels of assistance, from just training, to
consulting, to commercial versions of the software that simplify
certain processes and offer extended features.

At the very minimum, we recommend that you take a training course
on CFEngine. Users who don't train often end up using only a fraction
of the software's potential, and in a sub-optimal way. Think of this
as an investment in your future.

The advantages of the commercial products include greatly simplified
set up procedures, continuous monitoring and automatic knowledge
integration. See the CFEngine Nova Supplement for more information.

@node Installation or Pilot, Identifying the Team, Commercial or Free?, Top
@unnumberedsec Installation or Pilot
@sp 1

You are free to download Community Editions of CFEngine at any time to
test the software. There is a considerable amount of documentation and
example policy available on the CFEngine.org and CFEngine.com web-sites
to try some simple examples of system management.

If you intend to purchase a significant number of commercial licenses
for CFEngine software, you can request a pilot process, during which a
specialist will install and demonstrate the commercial edition on
site.

@node Identifying the Team, Training and Certification, Installation or Pilot, Top
@unnumberedsec Identifying the Team
@sp 1

CFEngine will become a core discipline in your organization, taking
you from reactive fire-fighting to proactive and strategic
practices. You should invest in a team that embraces its methods. The
CFEngine team will become the enabler of business agility, security,
reliability and standardization.

The CFEngine team needs to have administrator or super-user access
to systems, and it needs the `headroom' or `slack' to think
strategically. It needs to build up processes and workflows that
address quality assurance and minimize the risk of change.

All teams are important centres for knowledge, and you should provide
incentives to keep the core team strong and in constant dialogue with
your organization's strategic leadership. Treat your CFEngine team as
a trusted partner in business.

@node Training and Certification, Mission Goal and Knowledge Management, Identifying the Team, Top
@unnumberedsec Training and Certification
@sp 1

Once you have tried the simplest examples using CFEngine, we recommend
at least three days of in-depth training. We can also arrange more
in-depth training to qualify as a CFEngine Mission Specialist.

@node Mission Goal and Knowledge Management, Build, Training and Certification, Top
@unnumberedsec Mission Goal and Knowledge Management
@sp 1

The main aim of Knowledge Management is to learn from experience, and
use the accumulated learning to improve the predictability of workflow
processes. During every mission, there will be unexpected events, and
an effective team will use knowledge of past and present to respond to
these unpredictable changes with confidence

The goal of an IT mission is a @i{predictable operational state} that
lives up to specific policy-determined promises. You need to work out
what this desired state should be before you can achieve it. No one
knows this exactly in advance, and most organizations will change
course over time. However, with good planning and understanding of the
mission, such adjustments to policy can be small and regular. 

@sp 1

@cartouche

Many small changes are less risky than few large changes, and the
culture of agility keeps everyone on their toes. Using CFEngine to run
your mission, you will learn to work pro-actively, adjusting the system
by refining the mission goal rather than reacting to unexpected
events.

@end cartouche

@sp 1
To work consistently and predictably, even when understaffed, requires
a strategy for describing system resources, policy and state.
CFEngine can help with all of these. See the Special Topics Guide on
Knowledge Management.

A major component of a successful mission, is documenting
@i{intentions}.  What is the goal, and how does it break down into
concrete, achievable states? CFEngine can help you in this process,
with training and Professional Services,  but you must establish a
culture of commitment to the mission and learn how to express these
commitments in terms of CFEngine @i{promises}.

@node Build, Contact CFEngine, Mission Goal and Knowledge Management, Top
@unnumberedsec Build, Deploy, Manage, Audit
@sp 1

The four mission phases are sometimes referred to as 

@table @emph
@item Build
A mission is based on decisions and resources that need to
be put assembled or `built' before they can be applied. This is
the planning phase.

In CFEngine, what you build is a template of proposed promises for the
machines in an organization such that, if the machines all make and
keep these promises, the system will function seamlessly as
planned. This is how it works in a human organization, and this is how
is works for computers too.

@item Deploy
Deploying really means launching the policy into production.  In
CFEngine you simply publish your policy (in CFEngine parlance these
are `promise proposals') and the machines see the new proposals and
can adjust accordingly. Each machine runs an agent that is capable of
keeping the system on course and maintaining it over time without
further assistance.

@item Manage
Once a decision is made, unplanned events will occur. Such incidents
traditionally set off alarms and humans rush to make new transactions
to repair them. Under CFEngine guidance, the autonomous agent manages
the system, and humans only manage knowledge and have to deal with
rare events that cannot be dealt with automatically.

@item Audit
CFEngine performs continuous analysis and correction, and commercial
editions generate explicit reports on mission status.  Users can sit
back and examine these reports to check mission progress, or examine
the current state in relation to the knowledge map for the mission.

@end table

@node Contact CFEngine,  , Build, Top
@unnumberedsec Contact CFEngine
@sp 1

Contact CFEngine today for more information: @code{contact@@CFEngine.com}.


@ifhtml
@html
<a name="Contents">
@contents
@end html
@end ifhtml

@ifhtml
@html
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https:// 
ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google- 
analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2576171-2");
pageTracker._initData();
pageTracker._trackPageview();
</script>
@end html
@end ifhtml

@bye

