#!/usr/bin/zsh

T='1 2 3 4 5 6 7 8 9 10 50 100 200 500 1000 2000'

for threads in $(echo $T); do
    echo "$threads threads..."
    SUMT=0
    for i in $(seq 1 10); do
      TIME=$(/usr/bin/time --format '%e' ./tcdb_load $threads 2>&1)
      SUMT=$(($SUMT+$TIME))
    done
    SUMT=$(($SUMT/10))
    printf "%d %f %f\n" $threads $SUMT $(($SUMT / $threads))
done
