.TH cf-promises 8 "Maintenance Commands"
.SH NAME
cf-promises - cfengine's promise analyzer

.SH SYNOPSIS:

 cf-promises [options]

.SH DESCRIPTION:

The promise agent is a validator and analysis tool for
configuration files belonging to any of the components
of Cfengine. Configurations that make changes must be
approved by this validator before being executed.
.B cfengine
is a self-healing configuration and change management based system. You can think of.B cfengine
as a very high level language, much higher level than Perl or shell. Asingle statement is called a promise, and compliance can result in many hundreds of filesbeing created, or the permissions of many hundreds offiles being set. The idea of .B cfengine
is to create a one or more sets of configuration files which willclassify and describe the setup of every host in a network.
.SH COMMAND LINE OPTIONS:
.IP "--help, -h"
Print the help message
.IP "--debug, -d" value
Set debugging level 0,1,2,3
.IP "--verbose, -v"
Output verbose information about the behaviour of the agent
.IP "--dry-run, -n"
All talk and no action mode - make no changes, only inform of promises not kept
.IP "--version, -V"
Output the version of the software
.IP "--file, -f" value
Specify an alternative input file than the default
.IP "--define, -D" value
Define a list of comma separated classes to be defined at the start of execution
.IP "--negate, -N" value
Define a list of comma separated classes to be undefined at the start of execution
.IP "--inform, -I"
Print basic information about changes made to the system, i.e. promises repaired
.IP "--diagnostic, -x"
Activate internal diagnostics (developers only)
.IP "--analysis, -a"
Perform additional analysis of configuration
.IP "--reports, -r"
Generate reports about configuration and insert into CFDB
.SH AUTHOR
Mark Burgess and Cfengine AS
.SH INFORMATION

Bug reports: bug-cfengine@cfengine.org
.pp
Community help: help-cfengine@cfengine.org
.pp
Community info: http://www.cfengine.org
.pp
Support services: http://www.cfengine.com
.pp
This software is Copyright (C) 2008- Cfengine AS.
