.TH cfengine 8 "Maintenance Commands"
.SH NAME
cfpromises \- promise compiler for cfengine 3
.SH SYNOPSIS
/usr/local/sbin/cfpromises [options]

.SH DESCRIPTION
.B cfengine
is a language based system specifically designed
for testing and configuring unix\-like systems attached to
a TCP/IP network. 
.PP
Cfengine policy is defined as a number of promises about
the basic resources in a computer. Each resource promises
to uphold certain properties described in the configuration.
.B cfagent
then performs host integrity and security checks as well
as installing and repairing system configuration.

.PP
The present version of this program is only a training version.
The full cfengine 3 deployment is estimated for the end of 2008.

.SH COMMAND LINE OPTIONS
.IP "-f (--file)"
Parse filename after this switch. By default 
.B cfagent
looks for a file called promises.cf in the working directory (usually
/var/cfengine/inputs).
.IP "-h (--help )"
Help information. Display version banner and options summary.
.SH AUTHOR
Mark Burgess, Oslo University College
.SH INFORMATION
http://www.cfengine.org

