/*******************************************************************/
/*../tests/units/unit_chdir.cf */

char *O_CHDIR_TEXT = "O_CHDIR";
char *O_CHDIR = "Q: \".../bin/pwd\": /tmp\n\
I: Last 1 QUOTed lines were generated by promiser \"/bin/pwd\"\0";

/*******************************************************************/
/*../tests/units/lists.cf */

char *O_LISTS_TEXT = "O_LISTS";
char *O_LISTS = "R: global var: 1\n\
R: global var: 2\n\
R: global var: 3\n\
R: local var: 1\n\
R: local var: 2\n\
R: local var: 3\n\
R: local var: 4\n\
R: local var: 5\n\
R: test var: $(def.global)\n\
R: g string: hello world\n\
R: l string: Biswha, hello world\n\
R: test1 string: xxx\n\
R: test1 slist1: $(test1.xslist)\n\
R: test1 slist2: one\n\
R: test1 slist2: two\n\
R: test1 slist2: three\0";

/*******************************************************************/
/*../tests/units/unit_classvar_convergence.cf */

char *O_CLASSVAR_CONVERGENCE_TEXT = "O_CLASSVAR_CONVERGENCE";
char *O_CLASSVAR_CONVERGENCE = "R: List substitution works\n\
R: Evaluated true\0";

/*******************************************************************/
/*../tests/units/unit_dollar.cf */

char *O_DOLLAR_TEXT = "O_DOLLAR";
char *O_DOLLAR = "R: The value of $(const.dollar) is $\n\
R: But the value of \\$(dollar) is \\$(dollar)\0";

/*******************************************************************/
/*../tests/units/insert_lines.cf */

char *O_INSERT_LINES_TEXT = "O_INSERT_LINES";
char *O_INSERT_LINES = "! Test configuration file, generated by Cfengine\n\
                vrrp_instance R1 {\n\
           state MASTER\n\
           interface eth0\n\
         virtual_router_id 15\n\
    priority 100\n\
     advert_int 1\n\
    virtual_ipaddress\n\
       {\n\
         ! master interfaces\n\
  10.0.0.3 label eth0:3\n\
  10.0.0.2 label eth0:2\n\
  10.0.0.1 label eth0:1\n\
       }\n\
        }";

/*******************************************************************/

