name: Build and unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get install -y libssl-dev libpam0g-dev liblmdb-dev byacc curl
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug
    - name: Compile and link (make)
      run: make
    - name: Run unit tests
      run: cd tests/unit && make check
