#!/usr/bin/perl
# Author: Nick Anderson <nick@cmdln.org>, Ted Zlatanov <tzz@lifelogs.com>
# locate and show bundles or bodies in a list of paths

use strict;
use warnings;
use File::Find;
use Term::ANSIColor;

my $full = 0;
my $regex = shift @ARGV;

if ($regex eq '-f' || $regex eq '--full')
{
 $full = 1;
 $regex = shift @ARGV;
}

die "Syntax: $0 [-f|--full] BODY-OR-BUNDLE-REGEX PATH1 PATH2 ...\n"
 unless scalar @ARGV > 0;

my @search = @ARGV;

find(\&wanted, @search);

sub wanted
{
 open my $f, '<', $_;
 my $found = 0;
 my $highlight = 0;
 my $current = "green";

 while (<$f>)
 {
  if (m/^\s*(body|bundle).*$regex/)
  {
   $found = 1;
   $highlight = 1;
   print color($current);
   print "-> body or bundle matching '$regex' found in $File::Find::name:$.";
   print color("reset"), "\n";

   $current = "red";
  }

  if ($found)
  {
   print color($current) if ($highlight);
   print;
   $current = "yellow";
  }

  if (!$full || m/^\s*}\s*$/)
  {
   $found = 0;
  }
 }
 print color("reset") if $highlight;
}
